### ISSUE TITLE
输入番号后搜索不到内容

### ISSUE THREAD

**Issue by dannyc97230** [levywang/avhub#19]
容器能够正常启动，但搜索不到结果，日志如下
INFO:     Started server process [7]

INFO:     Waiting for application startup.

[2025-05-01 04:28:31,687][utils.logger][INFO] - Application startup

INFO:     Application startup complete.

INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

[2025-05-01 04:28:45,155][utils.logger][INFO] - HACG data fetched successfully

INFO:     27.10.216.161:0 - "GET /v1/hacg HTTP/1.1" 200 OK

[2025-05-01 04:28:45,158][utils.logger][INFO] - Retrieved top 10 popular search terms from last 2000 lines

INFO:     27.10.216.161:0 - "GET /v1/hot_searches HTTP/1.1" 200 OK

[2025-05-01 04:28:52,320][utils.logger][ERROR] - Error fetching https://missav.ai/cn/search/sdde-318: HTTP Error 403: 

[2025-05-01 04:28:52,321][utils.logger][ERROR] - No magnet links found for AV code: sdde318

[2025-05-01 04:28:52,321][utils.logger][ERROR] - Error processing AV code sdde318: 404: No magnet links found

INFO:     27.10.216.161:0 - "GET /v1/avcode/sdde-318 HTTP/1.1" 500 Internal Server Error

**Comment by levywang** [comment]
如果你部署的服务器在境内的话，需要配置代理，编辑config文件，配置如下：
```
av_spider:
  source_url: "https://missav.ai/cn/search/"
  proxy_url: "http://192.168.50.3:7890" # http or socks5 proxy
  use_proxy: true
```

proxy_url 是http代理服务器地址，因为missav在境内是被墙了
